# application.yml
# YML文件格式是YAML (YAML Aint Markup Language)编写的文件格式,YAML是一种直观的能够被电脑识别的的数据数据序列化格式,他并且容易被人类阅读.
# 注意：yml的缩进，使用空格符，而不要使用tab键

# project相关
project:
    artifactId: elven-cloud-config-test
    name: config-test
    description: config-test.cloud.elven.tech

# 应用相关
app:
    name: elven-cloud-config-test
    description: ${app.name} is a Spring Cloud config-test application

application:
    message: Hello, elven, i am in elven-cloud-config-test.yml.

# 应用信息
info:
    contact.email: elven1984@gmail.com
    contact.phone: 18888888888
    app.name: ${app.name}
    app.description: ${app.name} is a Spring Cloud config-test application

# 服务器设置（端口等）
server:
    port: 9100 # 0:随机端口, -1表示禁止HTTP端口
    undertow:
        accesslog:
            enabled: true

# 日志
logging:
    level:
        root: INFO #FATAL ERROR WARN INFO DEBUG TRACE
    path: ./    # ./表示当前应用的根目录
    file: ./logs/elven-cloud-config-test.log    # 设置日志文件


# spring
spring:
    cloud:
        bus:
            trace:
                enabled: true

# 关闭安全验证
management:
    security:
        enabled: false