# application.yml
# YML文件格式是YAML (YAML Aint Markup Language)编写的文件格式,YAML是一种直观的能够被电脑识别的的数据数据序列化格式,他并且容易被人类阅读.
# 注意：yml的缩进，使用空格符，而不要使用tab键

# project相关
project:
    artifactId: elven-cloud-eureka-server
    name: eureka-server
    description: eureka-server.cloud.elven.tech

# 应用相关
app:
    name: elven-cloud-eureka-server
    description: ${app.name} is a Spring Cloud Eureka application

application:
    message: Hello, Eureka

# 应用信息
info:
    contact.email: elven1984@gmail.com
    contact.phone: 18888888888
    app.name: ${app.name}
    app.description: ${app.name} is a Spring Cloud Eureka application

# 服务器设置（端口等）
server:
    port: 9000 # 0:随机端口, -1表示禁止HTTP端口
    undertow:
        accesslog:
            enabled: true

# 日志
logging:
    level:
        root: INFO #FATAL ERROR WARN INFO DEBUG TRACE
    path: ./    # ./表示当前应用的根目录
    file: ./logs/elven-cloud-eureka-server.log    # 设置日志文件

# application管理（监控）服务相关设置
management:
    address: 127.0.0.1
    # port:-1表示不能通过http访问管理服务
    port: 9100
    context-path: /manage
    security:
        enabled: false

# 管理监控点设置
endpoints:
    enabled: true
    sensitive: false
    cors:
        allowed-origins: http://example.com
        allowed-methods: GET,POST
    actuator:
        id: actuator
        path: /actuator
        enabled: true
        sensitive: true
    autoconfig:
        id: autoconfig
        path: /actuator/autoconfig
        enabled: true
        sensitive: true
    beans:
        id: beans
        path: /actuator/beans
        enabled: true
        sensitive: false
    configprops:
        id: configprops
        path: /actuator/configprops
        enabled: true
        sensitive: true
    docs:
        id: docs
        path: /actuator/docs
        enabled: true
        sensitive: true
    dump:
        id: dump
        path: /actuator/dump
        enabled: true
        sensitive: true
    env:
        id: env
        path: /actuator/env
        enabled: true
        sensitive: true
    flyway:
        id: flyway
        path: /actuator/flyway
        enabled: true
        sensitive: true
    health:
        id: health
        path: /actuator/health
        enabled: true
        sensitive: true
        # 缓存时间（毫秒）
        time-to-live: 1000
    info:
        id: info
        path: /actuator/info
        enabled: true
        sensitive: true
    liquibase:
        id: liquibase
        path: /actuator/liquibase
        enabled: true
        sensitive: true
    logfile:
        id: logfile
        path: /actuator/logfile
        enabled: true
        sensitive: true
    metrics:
        id: metrics
        path: /actuator/metrics
        enabled: true
        sensitive: true
    mappings:
        id: mappings
        path: /actuator/mappings
        enabled: true
        sensitive: true
    shutdown:
        id: shutdown
        path: /actuator/shutdown
        enabled: true
        sensitive: true
    trace:
        id: trace
        path: /actuator/trace
        enabled: true
        sensitive: true

# banner-mode
spring:
    main:
        banner-mode: "off"
    profiles:
        active: home
    # rabbitmq配置
    rabbitmq:
        host: 101.200.189.84
        port: 5672
        virtualHost: /test
        username: test
        password: test

# eureka server
eureka:
  server:
      enable-self-preservation: true  # 设为false，关闭自我保护
      eviction-interval-timer-in-ms: 4000  # 清理间隔（单位毫秒，默认是60*1000）
  client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
          defaultZone: http://zone1:9000/eureka/, http://zone2:9001/eureka/
  instance:
      hostname: localhost
      metadataMap:
          instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      lease-expiration-duration-in-seconds: 30  # 续约更新时间间隔（默认30秒）
      lease-renewal-interval-in-seconds: 90  # 续约到期时间（默认90秒）